/**
 * auto generated by dubbo dj
 * ~~~ 💗 machine coding 💗 ~~~
 */

import { User, IUser } from '../entity/User'
import UserService from './base/UserService'

export default class UserServiceImpl extends UserService {
  async sayHello(sayHello: IUser): Promise<IUser> {
    throw new Error('Not implemented sayHello method')
  }

  async sayWorld(sayWorld: Array<string>): Promise<string> {
    throw new Error('Not implemented sayWorld method')
  }
}
