import Deps from './java-deps'

export default class Base {
  deps: Deps = new Deps()

  cls2Path(cls: string) {
    return cls.replace(/\./g, '/')
  }

  buildComment(comment?: string) {
    return comment
      ? `
    /**
    * ${comment}
    */
   `
      : ''
  }

  get mott() {
    return `
      /**
       * auto generated by dubbo dj
       * ~~~ mechine coding 💗 ~~~~
       */
    `
  }
}
